version: '3'

services:
  zsss-redis:
    restart: always
    image: redis:latest
    container_name: redis
    command:
      # 执行的命令
      redis-server /etc/redis/redis.conf
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - D:\idea\workspace\spring-cloud-demo\docker\redis\conf:/etc/redis/redis.conf:rw
      - D:\idea\workspace\spring-cloud-demo\docker\redis\data:/data:rw
    ports:
      - "6379:6379"
